# Generated by Django 2.2.6 on 2019-11-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
