# Generated by Django 2.2.6 on 2019-11-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
