# Generated by Django 2.2.6 on 2019-10-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iv', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='document',
            new_name='imagefile',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='name',
        ),
    ]
