# Generated by Django 2.2.6 on 2019-10-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv', '0003_auto_20191030_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
