# Generated by Django 2.2.6 on 2019-10-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iv', '0004_auto_20191030_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='description',
        ),
    ]
